name: Check Pull Requests

on:
  push:
    branches:
      - main
    paths:
      - './apps/server/**'

jobs:
  check-pull-requests:
    name: Check Pull Requests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: docker build -t tanzeem-app ./apps/server
      