version: '3.9'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tanzeem
      POSTGRES_USER: tanzeem
      POSTGRES_PASSWORD: tanzeem
    networks:
      - tanzeem
volumes:
  pgdata:
networks:
  tanzeem: